#LU CONFIG
#FOR COSTUM PLUGINS, DM ME ON DISCORD
#THIS PLUGIN IS MADE BY THEBJOREDCRAFT
#SUPPORT ON DISCORD: https://discord.gg/tEx5B2pJ
#YOU CAN USE COLORCODES WITH §!

#MainPrefix: "LuckUtils | "
#ErrorPrefix: "[ERROR] LuckUtils | "
#: "[WARN] LuckUtils | "
#InfoLuckUtils: "[INFO] LuckUtils | "

#  PLAYERLIST - TABLIST ----------------------------------------------

#PLACEHOLDER:
#%luckperms_prefix% = Gives the Prefix of the Player
#%playername% = Gives the Playername of the Player
#%registered%

PlayerListNameFormat: "%playername% %registered%"
PlayerListHeader: "MY NETWORK"
PlayerListFooter: "LuckUtils v2.1"
UpdateTabList: true
#IN TICKS - 20 Ticks = 1 sec
Repeat: 20

# CHATFORMAT --------------------------------------------------------

#PLACEHOLDER:
#%luckperms_prefix% = Gives the Prefix of the Player
#%playername% = Gives the Playername of the Player
#%message% = Returns the Message
#%afk% - If the player is afk, is it here

ChatFormat: "%playername% §8>>§r %message%"

# AFK ---------------------------------------------------------------

#PLACEHOLDER:
#%luckperms_prefix% = Gives the Prefix of the Player
#%playername% = Gives the Playername of the Player

AfkPermisson: "lu.afk"

#on:
Chatmessageon: "%playername% ist nun AFK"
TabFormaton: "§7[AFK]"

#off:
Chatmessageoff: "%playername% ist nun nicht mehr AFK"
TabFormatoff: ""

# Registered --------------------------------------------------------

RegPermisson: "lu.registered"
RegFormatOn: "✓"
RegFormatOff: ""